import type { WebEngineAPI } from "sprig/web";

export const player = "p";

export const initializePlayer = (api: WebEngineAPI) => {
    const { onInput, afterInput, getFirst, setLegend, bitmap } = api;

    setLegend([
        player,
        bitmap`
................
................
.......000......
.......0.0......
......0..0......
......0...0.0...
....0003.30.0...
....0.0...000...
....0.05550.....
......0...0.....
.....0....0.....
.....0...0......
......000.......
......0.0.......
.....00.00......
................`,
    ]);

    onInput("s", () => {
        const p = getFirst(player);

        if (p) p.y += 1;
    });

    afterInput(() => {});
};
